version: '3'
services:

  postgres:
    image: "postgres:15.2-alpine"
    container_name: ecommerce-postgres
    restart: always
    volumes:
      - ./docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker-postgres-init.sql
      - ecommerce-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks: 
      - ecommerce-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  
  pgadmin:
    image: dpage/pgadmin4
    environment: 
        PGADMIN_DEFAULT_EMAIL: "anna.goku1981@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "test123!"
    volumes:
      - pg-admin-data:/var/lib/pgadmin
    networks: 
      - ecommerce-network
    ports: 
        - "16543:80" #porta esposta dal c : immagine esposta dall'immagine
    depends_on: 
        - postgres  

  redis:
    image: redis:alpine3.16
    container_name: ecommerce-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks: 
      - ecommerce-network
        
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      #REDIS_PASSWORD: ${REDIS_PASSWORD}
      #HTTP_USER: admin
      #HTTP_PASSWORD: root
    ports:
      - 8081:8081
    networks:
      - ecommerce-network



networks:
  ecommerce-network:
    driver: bridge

volumes:
  ecommerce-data:
  pg-admin-data:
  redis-data:
